version: "2"

services:
  ide:
    image: monstrs/cloud9
    volumes:
      - ./:/workspace
    ports:
      - "8489:80"

  yarn:
    image: node
    working_dir: /workspace
    volumes:
      - ./:/workspace
    entrypoint: yarn
